### ISSUE TITLE
HTTP status code 400: Bad Request when creating new SMP ServiceGroup

### ISSUE THREAD

**Issue by beckjensen** [phax/phoss-smp#152]
For the first time we have encountered an error message when creating a Service Group. We get the message
'The server sent HTTP status code 400: Bad Request'

<img width="1392" alt="Error creating a service group in Phoss" src="https://user-images.githubusercontent.com/44839825/104582051-b4cabf00-565f-11eb-9a71-f453f5afb179.png">

We are using a production SMP certificate and phoss SMP 5.3.1

**Comment by phax** [comment]
Hello. Is it on test or production? (SMK or SML?)
CEF recently did a cleanup and removed certain entries from the SMK/SML - yours *may* be one of those

**Comment by phax** [comment]
What I need to know from all of you having this problem, are the following parameters:
* Are you on SML or on SMK?
* What is your SMP-ID (you can see it in angle brackets in the header - like "DIGITALCAB" in the screenshot of the top post)
* An example participant ID registered on your SMP

**Comment by ic-officient** [comment]
> Hello. Is it on test or production? (SMK or SML?)
> CEF recently did a cleanup and removed certain entries from the SMK/SML - yours _may_ be one of those

It is production. I wrote to CEF Support yesterday. But that did not give me any clues.

**Comment by phax** [comment]
@ic-officient please provide me with the details according to https://github.com/phax/phoss-smp/issues/152#issuecomment-760168480

**Comment by ic-officient** [comment]
> What I need to know from all of you having this problem, are the following parameters:
> 
> * Are you on SML or on SMK?
> * What is your SMP-ID (you can see it in angle brackets in the header - like "DIGITALCAB" in the screenshot of the top post)
> * An example participant ID registered on your SMP

Production: SML
SMP-ID: OFFICIENT-PEPPOL
Participant ID: 0184:13522197  (in MYSQL database tables, but not findable from SMP manager)

**Comment by beckjensen** [comment]
Hi phax,

 - We are on SML

 - Our SMP-ID in the angle brackets is DIGITALCAB

 - An example would be 0088:5790001394486 
 - https://peppol.helger.com/public/locale-en_US/menuitem-tools-participant?scheme=iso6523-actorid-upis&value=0088%3A5790001394486&sml=autodetect&querybc=true&__querybc=true&__showtime=true&xsdvalidation=true&__xsdvalidation=true&verifysignatures=true&__verifysignatures=true&action=perform 

 - Another example 0088:5790002240379
 - https://peppol.helger.com/public/locale-en_US/menuitem-tools-participant?scheme=iso6523-actorid-upis&value=0088%3A5790002240379&sml=autodetect&querybc=true&__querybc=true&__showtime=true&xsdvalidation=true&__xsdvalidation=true&verifysignatures=true&__verifysignatures=true&action=perform

**Comment by phax** [comment]
(in a meeting - will respond asap afterwards)

**Comment by phax** [comment]
@beckjensen  your SMP entries look good - I can look up everything properly. Did you eventually recently received new Peppol certificates? If so, did you update them at the SML?

**Comment by phax** [comment]
@ic-officient Ivan, you had the problem than an entry was created but the creation in the SML failed. Did you previously update the SMP version or did you receive a new Peppol SMP certificate? I also saw, that you current disabled SML connection....

**Comment by ic-officient** [comment]
> @ic-officient Ivan, you had the problem than an entry was created but the creation in the SML failed. Did you previously update the SMP version or did you receive a new Peppol SMP certificate? I also saw, that you current disabled SML connection....

@phax yes we got a new certificate a couple of month ago (late October). I will reenable the SML connection. I can remember when I changed to version 5.3.1.

**Comment by phax** [comment]
Okay, do you know if you have created a participant in the SML since the last certificate update?

**Comment by ic-officient** [comment]
> Okay, do you know if you have created a participant in the SML since the last certificate update?

Yes, as far as I can tell from my mailbox, my calendar and our certificate, I believe  0088:7332545041792 was registered October 27. or after and our certificate was updated between October 15. and 18.

**Comment by phax** [comment]
Here are some additional reasons what HTTP 400 could mean: https://github.com/phax/phoss-smp/wiki/SML-notes#generic-error-codes

**Comment by beckjensen** [comment]
> @beckjensen your SMP entries look good - I can look up everything properly. Did you eventually recently received new Peppol certificates? If so, did you update them at the SML?

Yes, we installed a new production certificate last weekend and got it registered/updated via CEF-EDELIVERY-SUPPORT@ec.europa.eu 

Just now I registered the service group 0088:5790002107856 to make sure that everything works after the certificate change and the new entry gave no problems, as seen below

<img width="1918" alt="Skærmbillede 2021-01-15 kl  10 12 19" src="https://user-images.githubusercontent.com/44839825/104705679-8362f980-571a-11eb-964c-c7d5405fe527.png">

<img width="1394" alt="Skærmbillede 2021-01-15 kl  10 12 35" src="https://user-images.githubusercontent.com/44839825/104705717-8d84f800-571a-11eb-9991-bd88316220f4.png">

**Comment by phax** [comment]
Great @beckjensen  so your issue is resolved 👍🏼

**Comment by phax** [comment]
@ic-officient I think you need to wait for CEF support - sorry

**Comment by beckjensen** [comment]
Unfortunately not, the problem with registering the GLN 0088:5790002590993 is still the same while registrations of other GLN's just works :-)

**Comment by phax** [comment]
According to https://peppol.helger.com/public/locale-en_US/menuitem-tools-participant?scheme=iso6523-actorid-upis&value=0088%3A5790002590993&sml=autodetect&querybc=true&__querybc=true&__showtime=true&xsdvalidation=true&__xsdvalidation=true&verifysignatures=true&__verifysignatures=true&action=perform the participant is already registered to your SMP....

To get it into your SMP do the following:
1. Goto "SMP Settings" and disable SML usage
2. Create the Service group locally (without writing to the SML because it's already there)
3. Goto "SMP Settings" and re-enable SML usage
4. Create the endpoints as you desire

**Comment by beckjensen** [comment]
That solved our problem, thanks and have a nice weekend :-)
